version: '3.9'

services:
  devel_image:
    image: custom_devel-image
    build:
      context: .
    container_name: custom_devel-container
    network_mode: host
    gpus: all
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw # GUI 

    - /dev:/dev
    - ${XAUTHORITY}:/tmp/.docker.xauth

    - /mnt:/mnt
    - /home/${USER}/Desktop:/Desktop
    privileged: true
    environment:
      - DISPLAY=${DISPLAY} # GUI
      - QT_X11_NO_MITSHM=1 # GUI
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=59
    tty: true # Terminal
    # entrypoint: [""]

    
